name: letscode-backend
namespace: backend

image:
  repository: rafacaumo/letscode-backend

deployment:
  port: 8080
  enableHeathCheck: true
  healthCheckPath: /actuator
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 200m

ingress:
  prefix: api.