name: letscode-backend
namespace: backend

image:
  repository: rafacaumo/letscode-backend

deployment:
  port: 8080
  enableHeathCheck: true
  healthCheckPath: /actuator
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1024Mi
      cpu: 500m

ingress:
  prefix: api.